### PR TITLE
Update to petgraph 0.6

### PR DESCRIPTION
**Pull request by aentity**

### CODE REVIEW

**Comment by aentity** [comment]
oh i see petgraph is in public api unfortunately. i think it means we must make 0.3, is it correct @mitchmindtree ?

**Comment by aentity** [comment]
ok updated thank you!

**Comment by mitchmindtree** [comment]
Thanks!

**Comment by aentity** [comment]
great thank you! can we have crates release ?

**Comment by aentity** [comment]
i see is done already, thank you!

**Comment by mitchmindtree** [comment]
I updated the CI to automatically publish new versions merged into master in #7 just before merging this :+1:

**Pull request merged**
